services:
  sveltekit:
    build: ./
    ports:
      - "3000:5173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - wordpress
    environment:
      NODE_ENV: development
    networks:
      - sveltekit_network
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
    networks:
      - sveltekit_network
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sveltekit_network
volumes:
  wordpress_data:
  db_data:
networks:
  sveltekit_network:
    driver: bridge
